CREATE SYNONYM TBLBLOGCATEGORIES FOR &yourschema.TBLBLOGCATEGORIES;
CREATE SYNONYM TBLBLOGCOMMENTS FOR &yourschema.TBLBLOGCOMMENTS;
CREATE SYNONYM TBLBLOGENTRIES FOR &yourschema.TBLBLOGENTRIES;
CREATE SYNONYM TBLBLOGENTRIESCATEGORIES FOR &yourschema.TBLBLOGENTRIESCATEGORIES;
CREATE SYNONYM TBLBLOGENTRIESRELATED FOR &yourschema.TBLBLOGENTRIESRELATED;
CREATE SYNONYM TBLBLOGPAGES FOR &yourschema.TBLBLOGPAGES;
CREATE SYNONYM TBLBLOGSEARCHSTATS FOR &yourschema.TBLBLOGSEARCHSTATS;
CREATE SYNONYM TBLBLOGSUBSCRIBERS FOR &yourschema.TBLBLOGSUBSCRIBERS;
CREATE SYNONYM TBLBLOGTEXTBLOCKS FOR &yourschema.TBLBLOGTEXTBLOCKS;
CREATE SYNONYM TBLBLOGTRACKBACKS FOR &yourschema.TBLBLOGTRACKBACKS;
CREATE SYNONYM TBLUSERS FOR &yourschema.TBLUSERS;

